name: derflutterdr
description: Flutter Application For Dr Todo Little
version: 0.4.2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.4.0
  firebase_auth: ^0.16.0
  firebase_database: ^3.1.3
  cloud_firestore: ^0.13.5
  google_sign_in: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
